//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Photo { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool IsUpdated { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public string TextAr { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
